"""empty message

Revision ID: cec5155f3132
Revises: 
Create Date: 2024-06-14 17:10:12.929118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec5155f3132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('tb_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('rgs_time', sa.DateTime(), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('tb_about_me',
    sa.Column('me_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('me_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('me_id')
    )
    op.create_table('tb_article',
    sa.Column('art_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pub_time', sa.DateTime(), nullable=True),
    sa.Column('click_num', sa.Integer(), nullable=True),
    sa.Column('save_num', sa.Integer(), nullable=True),
    sa.Column('love_num', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tb_tag.tag_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('art_id')
    )
    op.create_table('tb_msg_board',
    sa.Column('bd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('bd_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('bd_id')
    )
    op.create_table('tb_photo',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_name', sa.String(length=128), nullable=False),
    sa.Column('photo_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('tb_comment',
    sa.Column('cmt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('art_id', sa.Integer(), nullable=True),
    sa.Column('cmt_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['art_id'], ['tb_article.art_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('cmt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_comment')
    op.drop_table('tb_photo')
    op.drop_table('tb_msg_board')
    op.drop_table('tb_article')
    op.drop_table('tb_about_me')
    op.drop_table('tb_user')
    op.drop_table('tb_tag')
    # ### end Alembic commands ###
